trigger:
- main

pool:
  name: MyPools  # Self-hosted agent pool
  demands:
    - agent.name -equals MyAgent

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Compatible with project
  displayName: 'Install Node.js'

# Step 2: Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Step 3: Build the project
- script: |
    npm run build
  displayName: 'Build React Project'

# Step 4: Debug directory structure
- script: |
    dir "$(System.DefaultWorkingDirectory)"
    dir "$(System.DefaultWorkingDirectory)\build"
  displayName: 'Debug Directory Structure'

# Step 5: Check build directory
- script: |
    if not exist "$(System.DefaultWorkingDirectory)\build" (
      echo "Error: Build directory not found!"
      exit 1
    )
  displayName: 'Check Build Directory'

# Step 6: Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)\build'
    ArtifactName: 'react-build'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
